### PR TITLE
Fix play/pause DOMException 

### LINKED ISSUE #129: DOMException: The play() request was interrupted by a call to pause() - The whole app breaks after this(Can't make incoming/outgoing calls).
This happens sporadically but when it does, it breaks everything 😞 
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().` This shows up in the console. 

[This stackoverflow question](https://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error) and [this](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted) sheds some light on when this could happen. I haven't gone through the web-phone sdk code yet. 

If anyone has any idea about this, please help.

### PR DESCRIPTION
**Pull request by mangatinanda**
Fixes #129

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Looks okay

@vyshakhbabji is it safe for merge?

**Comment by vyshakhbabji** [comment]
@mangatinanda  Can you give me the scenario of when the error you mentioned above happens? Can you provide the steps to generate this error? 

@kirill-konshin  I checked this pr and is safe to merge.

**Comment by kirill-konshin** [comment]
PlayPromise should not be a single instance, it should also be part of `this._audio[url]` object, because there are different sounds that can be played/paused.

**Comment by mangatinanda** [comment]
@vyshakhbabji It occurs sporadically while initiating the call(mainly, it occurs in other scenarios also). I was able to reproduce this in the heroku demo app but couldn't find the specific steps to reproduce. 
screen shot 2017-09-20 at 12 09 13 pm
I will update here if I could reproduce it consistently.

@kirill-konshin made code changes as per your comments.

**Comment by kirill-konshin** [comment]
@vyshakhbabji please verify.

**Comment by vyshakhbabji** [comment]
@kirill-konshin  I have verified and tested for webrtc features. We donot have the steps to reproduce or a reason for this error yet.

**Pull request merged**
