### PR TITLE
Handle US-Numbers + Build file merge resolutions

### PR DESCRIPTION
**Pull request by bdeanindy**
Left a TODO in place for improving this to support international numbers later, but for now (and the hackathon) this will work for US-numbers during SIP Registration.

### CODE REVIEW

**Comment by grokify** [comment]
The following is very limited in it's corrective nature.

```
username = (username.match(/^1/)) ? username : '1' + username;
```

Can we add a requirement for Google libphonenumber and do something more proper, like the following:

```
phoneUtils.formatE164(username, 'us');
```

Nathan Hammond has a pre-packaged version of Google libphonenumber ready to use:

* Google: https://github.com/googlei18n/libphonenumber
* Nathan Hammond's pre-built version: https://github.com/nathanhammond/libphonenumber

**Comment by kirill-konshin** [comment]
I don't like the idea to bloat the demo...

**Comment by kirill-konshin** [comment]
```js
username = (username.match(/^1/)) ? username : '1' + username;
```

This fix is OK.

**Comment by grokify** [comment]
```
username = (username.match(/^1/)) ? username : '1' + username;
```

This is a very limited fix that does not address other formatting issues.

If there's a desire not to add other dependencies, at least remove non 0-9 characters.

Since this was closed, the human readable numbers was opened as issue #44

**Pull request closed without merging**
